# arxivの学問領域の指定
subject: 'cat:astro-ph.SR OR cat:astro-ph.CO'

# 検索キーワード
keywords:
        protostar: 3
        envelope: 3
        ALMA: 3
        disk: 1
        model: 1
        infall: 4
        outflow: 1
        

# 通知の閾値
score_threshold: 0
